In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
# ^^^ pyforest auto-imports - don't write above this line
import pandas as pd

time: 3.41 s


In [4]:
df = pd.read_csv('Capstone_model_3.csv')

<IPython.core.display.Javascript object>

In [5]:
df

index      race  gender       age  admission_type_id  \
0          1  0.240931       0  0.151549           0.243674   
1          5  0.240931       1  0.219908           0.242545   
2          7  0.240931       1  0.244659           0.243674   
3         10  0.245193       0  0.238560           0.243674   
4         11  0.245193       1  0.240600           0.242545   
...      ...       ...     ...       ...                ...   
71085  12469  0.240931       1  0.241170           0.249835   
71086  72575  0.240931       0  0.241405           0.252307   
71087   6517  0.243329       1  0.238560           0.249523   
71088  92986  0.240931       0  0.242545           0.249283   
71089   9199  0.243994       0  0.241742           0.243674   

       discharge_disposition_id  admission_source_id    diag_1    diag_2  \
0                      0.206571             0.236728  0.263696  0.289953   
1                      0.206571             0.263651  0.231501  0.206477   
2                      0.206571             0.236728  0.234254  0.212776   
3                      0.206571             0.236728  0.250146  0.231240   
4                      0.206571             0.314975  0.285527  0.214526   
...                         ...                  ...       ...       ...   
71085                  0.308873             0.241521  0.350876  0.237429   
71086                  0.206571             0.243443  0.224244  0.218394   
71087                  0.319038             0.241278  0.269767  0.234706   
71088                  0.219715             0.241091  0.262024  0.229568   
71089                  0.280087             0.236728  0.234254  0.271454   

         diag_3  ...  rosiglitazone   insulin  change  diabetesMed  \
0      0.345712  ...       0.243954  0.252058       1            0   
1      0.234852  ...       0.243954  0.246712       0            0   
2      0.234852  ...       0.243954  0.229703       0            0   
3      0.290121  ...       0.243954  0.246712       0            0   
4      0.398817  ...       0.243954  0.246712       1            0   
...         ...  ...            ...       ...     ...          ...   
71085  0.247951  ...       0.243954  0.239434       0            0   
71086  0.259376  ...       0.243954  0.233078       0            0   
71087  0.217541  ...       0.243954  0.237475       0            0   
71088  0.351165  ...       0.243954  0.237853       0            0   
71089  0.275740  ...       0.243954  0.235993       1            0   

       time_in_hospital  num_medications  number_diagnoses  num_ovrll_prcdrs  \
0             -0.353541         0.352067          0.788793          0.699943   
1             -0.353541         0.095211          0.788793         -0.429853   
2              0.414600        -0.489932          0.022613          1.430210   
3              1.364225         0.226131          0.788793          0.183321   
4              0.951862        -0.655536         -0.603491          0.855788   
...                 ...              ...               ...               ...   
71085          0.721962         1.130808          0.788793          0.613429   
71086         -0.906393        -0.746248          0.022613         -1.482995   
71087         -0.353541        -0.407819         -0.776990         -0.729237   
71088         -0.135076         0.314446         -0.396589         -0.260814   
71089         -0.534686        -0.071351         -0.570228         -0.065269   

       num_prvs_vists  readmitted  
0           -1.052481           0  
1           -1.052481           0  
2           -1.052481           0  
3           -1.052481           0  
4           -1.052481           1  
...               ...         ...  
71085        0.222471           1  
71086       -0.030516           1  
71087       -0.226008           1  
71088        1.158414           1  
71089        0.247292           1  

[71090 rows x 27 columns]

In [6]:
X = df.drop('readmitted',axis=1)
y = df['readmitted']

In [7]:
X.drop('index',axis=1,inplace=True)

In [8]:
from pyforest import *

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=96)

<IPython.core.display.Javascript object>

In [10]:
import scipy.stats as st

In [11]:
#looking at only p-values
st.ttest_ind(X_train,X)[1]

array([0.86538653, 0.76809945, 0.66322909, 0.78607067, 0.97051764,
       0.768636  , 0.35899745, 0.67707881, 0.59010208, 0.96182293,
       0.95994185, 0.9501016 , 0.17094159, 0.80946102, 0.96460156,
       0.90111219, 0.44491859, 0.65211114, 0.91914351, 0.79259369,
       0.98042616, 0.95954466, 0.62027112, 0.90617218, 0.82214197])

In [12]:
st.ttest_ind(X_test,X)[1]

array([0.76615245, 0.60635083, 0.44590356, 0.63620428, 0.9484188 ,
       0.60714874, 0.11110204, 0.46397032, 0.34487458, 0.93340321,
       0.93014452, 0.91313069, 0.02722618, 0.67152647, 0.93801353,
       0.82798138, 0.17865737, 0.43256521, 0.85927131, 0.6464952 ,
       0.96576698, 0.92927974, 0.38712211, 0.83726732, 0.69479251])

In [13]:
st.ttest_ind(y_train,y)[1]

0.877046589999298

In [14]:
st.ttest_ind(y_test,y)[1]

0.7869657680912111

In [17]:
from sklearn.pipeline import Pipeline

In [25]:
from xgboost.sklearn import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from scipy.stats import randint
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
from sklearn.svm import SVC
import hyperopt as hp
from hyperopt import fmin, tpe, hp, Trials, STATUS_OK
from sklearn.model_selection import cross_val_score



In [9]:
# Create a pipeline
pipe = Pipeline([("classifier", XGBClassifier())])
# Create dictionary with candidate learning algorithms and their hyperparameters
r_param = [{"classifier": [LogisticRegression()],
                 "classifier__penalty": ['l2','l1'],
                 "classifier__C": np.logspace(0, 4, 10)},
               {"classifier": [LogisticRegression()],
                 "classifier__penalty": ['l2'],
                 "classifier__C": np.logspace(0, 4, 10),
                 "classifier__solver":['newton-cg','saga','sag','liblinear'] ##This solvers don't allow L1 penalty
                 },
            {"classifier": [DecisionTreeClassifier()],
             "classifier__criterion":['gini','entropy'],
                 "classifier__max_depth":[5,8,15,25,30,None],
                 "classifier__min_samples_leaf":[1,2,5,10,15,100],
                 "classifier__max_leaf_nodes": [2, 5,10]},
               {"classifier": [RandomForestClassifier()],
                 "classifier__n_estimators": [10, 100, 1000],
                 "classifier__max_depth":[5,8,15,25,30,None],
                 "classifier__min_samples_leaf":[1,2,5,10,15,100],
                 "classifier__max_leaf_nodes": [2, 5,10]},
           {'classifier':[LGBMClassifier()],
            'classifier__n_estimators':np.arange(50,250,5),
            'classifier__max_depth':np.arange(2,15),
            'classifier__num_leaves':np.arange(2,60,5)},
           {'classifier':[XGBClassifier()],
              "classifier__learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
            "classifier__min_child_weight" : [ 1, 3, 5, 7 ],
            "classifier__gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
            "classifier__colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]},
           #{'classifier':[SGDClassifier()],                                     ##Stocasticated Gradient decent
            #"classifier__C": [1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0],
            #"classifier__penalty": ['l2']},
           {'classifier':[AdaBoostClassifier()],        ## Adaboost Classifier
           "classifier__n_estimators": sp_randint(50,250), 
            'classifier__learning_rate': [(0.97 + x / 100) for x in range(0, 8)],
            'classifier__algorithm': ['SAMME', 'SAMME.R']},
           {'classifier':[KNN()],
            "classifier__weights":['uniform','distance'],
            'classifier__n_neighbors':np.arange(1,40),
            'classifier__leaf_size':np.arange(2,40)},
           {'classifier':[SVC()],                        ## SVM Algorithm
           'classifier__gamma':np.logspace(-4,2,10000),
       'classifier__C':np.logspace(-2,2,10000)},
           {"classifier":[GradientBoostingClassifier()],
            "classifier__learning_rate":np.arange(0,0.5,15),
            "classifier__n_estimators":np.arange(50,250,5),
            'classifier__max_depth':np.arange(2,15,5),
            "classifier__min_samples_leaf":[1,2,5,10,15,100],
            "classifier__max_leaf_nodes": [2, 5,10]}
          ]

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [26]:
from sklearn.model_selection import RandomizedSearchCV


In [11]:
rsearch = RandomizedSearchCV(pipe, r_param, cv=5, verbose=0,n_jobs=-1,random_state=96)

In [12]:
best_model_r = rsearch.fit(X_train,y_train)

time: 5min 47s


In [13]:
print(best_model_r.best_estimator_)
print("The mean accuracy of the model is through randomized search is :",best_model_r.score(X_test,y_test))

Pipeline(steps=[('classifier',
                 LGBMClassifier(max_depth=12, n_estimators=240,
                                num_leaves=22))])
The mean accuracy of the model is through randomized search is : 0.8425001172223003
time: 870 ms


In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,classification_report


time: 7 ms


In [15]:
best_model_r.best_params_

{'classifier': LGBMClassifier(max_depth=12, n_estimators=240, num_leaves=22),
 'classifier__max_depth': 12,
 'classifier__n_estimators': 240,
 'classifier__num_leaves': 22}

time: 17 ms


In [16]:
rfc=LGBMClassifier(max_depth=12, n_estimators=240,
                                num_leaves=22,random_state=96)
rfc.fit(X_train,y_train)
y_train_pred=rfc.predict(X_train)
y_train_prob=rfc.predict_proba(X_train)[:,1]

y_test_pred=rfc.predict(X_test)
y_test_prob=rfc.predict_proba(X_test)[:,1]

print('Confusion Matrix-Train\n',confusion_matrix(y_train,y_train_pred))
print('Accuracy Score-Train\n',accuracy_score(y_train,y_train_pred))
print('Classification Report-Train\n',classification_report(y_train,y_train_pred))

print('\n'*2)
print('Confusion Matrix-Test\n',confusion_matrix(y_test,y_test_pred))
print('Accuracy Score-Test\n',accuracy_score(y_test,y_test_pred))
print('Classification Report-Test\n',classification_report(y_test,y_test_pred))



Confusion Matrix-Train
 [[24626   233]
 [ 6686 18218]]
Accuracy Score-Train
 0.8609609549263509
Classification Report-Train
               precision    recall  f1-score   support

           0       0.79      0.99      0.88     24859
           1       0.99      0.73      0.84     24904

    accuracy                           0.86     49763
   macro avg       0.89      0.86      0.86     49763
weighted avg       0.89      0.86      0.86     49763




Confusion Matrix-Test
 [[10411   275]
 [ 3084  7557]]
Accuracy Score-Test
 0.8425001172223003
Classification Report-Test
               precision    recall  f1-score   support

           0       0.77      0.97      0.86     10686
           1       0.96      0.71      0.82     10641

    accuracy                           0.84     21327
   macro avg       0.87      0.84      0.84     21327
weighted avg       0.87      0.84      0.84     21327

time: 17.3 s


In [27]:
pipeline_lr=Pipeline([('lr',LogisticRegression(random_state=3))])

pipeline_dt=Pipeline([
                     ('dt',DecisionTreeClassifier(random_state=3))])

pipeline_rf=Pipeline([
                    ('rfc',RandomForestClassifier(random_state=3))])

pipeline_knn=Pipeline([
                     ('knn',KNN())])
pipeline_svm=Pipeline([('svc',SVC())])

In [28]:
pipelines=[pipeline_lr,pipeline_dt,pipeline_rf,pipeline_knn,pipeline_svm]

In [29]:
pipe_dict={0:'Logistic Regression',1:'Decision Tree',2:'Random Forest',3:'KNN',4:'SVM'}

In [31]:
from sklearn.metrics import classification_report,accuracy_score
for i in pipelines:
    i.fit(X_train,y_train)
    predictions=i.predict(X_test)
    print('Classification Report : \n',(classification_report(y_test,predictions)))

C:\Users\BramboArmy\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Classification Report : 
               precision    recall  f1-score   support

           0       0.66      0.68      0.67     10686
           1       0.67      0.65      0.66     10641

    accuracy                           0.67     21327
   macro avg       0.67      0.67      0.67     21327
weighted avg       0.67      0.67      0.67     21327

Classification Report : 
               precision    recall  f1-score   support

           0       0.75      0.73      0.74     10686
           1       0.74      0.76      0.75     10641

    accuracy                           0.75     21327
   macro avg       0.75      0.75      0.75     21327
weighted avg       0.75      0.75      0.75     21327

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.97      0.86     10686
           1       0.96      0.71      0.82     10641

    accuracy                           0.84     21327
   macro avg       0.86      0.84      0.84     21

In [32]:
for i,model in enumerate(pipelines):
    print('{} Test Accuracy {}'.format(pipe_dict[i],model.score(X_test,y_test)))
    


Logistic Regression Test Accuracy 0.6654475547428143
Decision Tree Test Accuracy 0.7471749425610729
Random Forest Test Accuracy 0.8395930041731139
KNN Test Accuracy 0.655366436910958
SVM Test Accuracy 0.6942842406339382


In [33]:
for i,model in enumerate(pipelines):
    print('{} Train Accuracy {}'.format(pipe_dict[i],model.score(X_train,y_train)))

Logistic Regression Train Accuracy 0.667303016297249
Decision Tree Train Accuracy 1.0
Random Forest Train Accuracy 1.0
KNN Train Accuracy 0.7731045154030103
SVM Train Accuracy 0.6979080843196752
