In [1]:
import pandas as pd

time: 1.74 s


In [2]:
df = pd.read_csv('Capstone_model_2.csv')

time: 1.89 s


In [3]:
df

race  gender       age  admission_type_id  \
0       0.464999       0  0.180299           0.532412   
1       0.464999       0  0.382066           0.472883   
2       0.457522       0  0.450212           0.472883   
3       0.464999       1  0.426756           0.472883   
4       0.464999       1  0.444502           0.472883   
...          ...     ...       ...                ...   
101758  0.457522       1  0.481240           0.472883   
101759  0.457522       0  0.482700           0.472883   
101760  0.464999       1  0.481240           0.472883   
101761  0.464999       0  0.482700           0.460931   
101762  0.464999       1  0.481240           0.472883   

        discharge_disposition_id  admission_source_id    diag_1    diag_2  \
0                       0.473202             0.431944  0.485229  0.288254   
1                       0.450242             0.493756  0.458419  0.513533   
2                       0.450242             0.493756  0.310664  0.414807   
3                       0.450242             0.493756  0.512721  0.513533   
4                       0.450242             0.493756  0.320982  0.488739   
...                          ...                  ...       ...       ...   
101758                  0.498924             0.493756  0.485229  0.393105   
101759                  0.468709             0.394165  0.471010  0.460311   
101760                  0.450242             0.493756  0.440711  0.460306   
101761                  0.498924             0.493756  0.494994  0.447715   
101762                  0.450242             0.493756  0.468307  0.496171   

          diag_3  max_glu_serum  ...  rosiglitazone   insulin  change  \
0       0.301602       0.459514  ...       0.459418  0.436999       0   
1       0.452887       0.459514  ...       0.459418  0.515376       1   
2       0.461196       0.459514  ...       0.459418  0.436999       0   
3       0.427601       0.459514  ...       0.459418  0.515376       1   
4       0.434835       0.459514  ...       0.459418  0.451068       1   
...          ...            ...  ...            ...       ...     ...   
101758  0.491480       0.459514  ...       0.459418  0.527909       1   
101759  0.464952       0.459514  ...       0.459418  0.451068       0   
101760  0.504323       0.459514  ...       0.459418  0.527909       1   
101761  0.445188       0.459514  ...       0.459418  0.515376       1   
101762  0.464952       0.459514  ...       0.459418  0.436999       0   

        diabetesMed  time_in_hospital  num_medications  number_diagnoses  \
0                 1         -1.632460        -3.304858         -2.125874   
1                 0         -0.271144         0.408817          0.865090   
2                 0         -0.825587        -0.237590         -0.909684   
3                 0         -0.825587         0.167145         -0.417314   
4                 0         -1.632460        -1.082723         -1.310201   
...             ...               ...              ...               ...   
101758            0         -0.271144         0.167145          0.865090   
101759            0          0.485715         0.408817          0.865090   
101760            0         -1.632460        -0.890313          4.757148   
101761            0          1.565616         0.738735          0.865090   
101762            1          0.766108        -2.392744          0.865090   

        num_ovrll_prcdrs  num_prvs_vists  readmitted  
0              -0.177270       -0.873587           0  
1               0.733542       -0.873587           1  
2              -1.431584        1.368394           0  
3               0.024705       -0.873587           0  
4               0.328150       -0.873587           0  
...                  ...             ...         ...  
101758          0.328150       -0.873587           1  
101759         -0.429334        0.648937           0  
101760          0.429416        0.648937           0  
101761          0.125792        0.648937           0  
101762 

time: 299 ms


In [4]:
X = df.drop('readmitted',axis=1)
y = df['readmitted']

time: 29 ms


In [5]:
from pyforest import *

time: 3.25 s


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=96)

<IPython.core.display.Javascript object>

time: 2.52 s


In [7]:
import scipy.stats as st

time: 4 ms


In [8]:
st.ttest_ind(X_train,X)[1]

array([0.91778603, 0.25023921, 0.82006251, 0.8280639 , 0.68618645,
       0.66737961, 0.96615346, 0.9999133 , 0.78088498, 0.66406555,
       0.75953404, 0.78761381, 0.4376827 , 0.9362097 , 0.85021965,
       0.89659287, 0.4705123 , 0.53579229, 0.37558116, 0.98160125,
       0.93097086, 0.88489858, 0.63353744, 0.89809475, 0.50560194])

time: 159 ms


In [9]:
st.ttest_ind(X_test,X)[1]

array([0.8574515 , 0.04468548, 0.69121614, 0.7026755 , 0.48198408,
       0.45441106, 0.9409104 , 0.99984796, 0.62636   , 0.45124564,
       0.59345267, 0.63776042, 0.18179503, 0.88874573, 0.74117005,
       0.82096593, 0.21347192, 0.27847334, 0.12155958, 0.96786943,
       0.87982918, 0.80062354, 0.40469962, 0.8226779 , 0.24461335])

time: 111 ms


In [19]:
from sklearn.pipeline import Pipeline

time: 999 µs


In [20]:
from xgboost.sklearn import XGBClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import SGDClassifier
from sklearn.neighbors import KNeighborsClassifier as KNN
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from lightgbm import LGBMClassifier
from scipy.stats import randint
from scipy.stats import randint as sp_randint
from scipy.stats import uniform as sp_uniform
from sklearn.svm import SVC
import hyperopt as hp
from hyperopt import fmin, tpe, hp, Trials, STATUS_OK
from sklearn.model_selection import cross_val_score



time: 19 ms


In [21]:
# Create a pipeline
pipe = Pipeline([("classifier", XGBClassifier())])
# Create dictionary with candidate learning algorithms and their hyperparameters
r_param = [{"classifier": [LogisticRegression()],
                 "classifier__penalty": ['l2','l1'],
                 "classifier__C": np.logspace(0, 4, 10)},
               {"classifier": [LogisticRegression()],
                 "classifier__penalty": ['l2'],
                 "classifier__C": np.logspace(0, 4, 10),
                 "classifier__solver":['newton-cg','saga','sag','liblinear'] ##This solvers don't allow L1 penalty
                 },
            {"classifier": [DecisionTreeClassifier()],
             "classifier__criterion":['gini','entropy'],
                 "classifier__max_depth":[5,8,15,25,30,None],
                 "classifier__min_samples_leaf":[1,2,5,10,15,100],
                 "classifier__max_leaf_nodes": [2, 5,10]},
               {"classifier": [RandomForestClassifier()],
                 "classifier__n_estimators": [10, 100, 1000],
                 "classifier__max_depth":[5,8,15,25,30,None],
                 "classifier__min_samples_leaf":[1,2,5,10,15,100],
                 "classifier__max_leaf_nodes": [2, 5,10]},
           {'classifier':[LGBMClassifier()],
            'classifier__n_estimators':np.arange(50,250,5),
            'classifier__max_depth':np.arange(2,15,5),
            'classifier__num_leaves':np.arange(2,60,5)},
           {'classifier':[XGBClassifier()],
              "classifier__learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
            "classifier__min_child_weight" : [ 1, 3, 5, 7 ],
            "classifier__gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
            "classifier__colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]},
           #{'classifier':[SGDClassifier()],                                     ##Stocasticated Gradient decent
            #"classifier__C": [1e-7, 1e-6, 1e-5, 1e-4, 1e-3, 1e-2, 1e-1, 1e0],
            #"classifier__penalty": ['l2']},
           {'classifier':[AdaBoostClassifier()],        ## Adaboost Classifier
           "classifier__n_estimators": sp_randint(50,250), 
            'classifier__learning_rate': [(0.97 + x / 100) for x in range(0, 8)],
            'classifier__algorithm': ['SAMME', 'SAMME.R']},
           {'classifier':[KNN()],
            "classifier__weights":['uniform','distance'],
            'classifier__n_neighbors':np.arange(1,40),
            'classifier__leaf_size':np.arange(2,40)},
           {'classifier':[SVC()],                        ## SVM Algorithm
           'classifier__gamma':np.logspace(-4,2,10000),
       'classifier__C':np.logspace(-2,2,10000)},
           {"classifier":[GradientBoostingClassifier()],
            "classifier__learning_rate":np.arange(0,0.5,15),
            "classifier__n_estimators":np.arange(50,250,5),
            'classifier__max_depth':np.arange(2,15,5),
            "classifier__min_samples_leaf":[1,2,5,10,15,100],
            "classifier__max_leaf_nodes": [2, 5,10]}
          ]

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

time: 462 ms


In [22]:
from sklearn.model_selection import RandomizedSearchCV


time: 8 ms


In [23]:
rsearch = RandomizedSearchCV(pipe, r_param, cv=5, verbose=0,n_jobs=-1,random_state=96)

time: 2.01 ms


In [24]:
best_model_r = rsearch.fit(X_train,y_train)

In [13]:
print(best_model_r.best_estimator_)
print("The mean accuracy of the model is through randomized search is :",best_model_r.score(X_test,y_test))

Pipeline(steps=[('classifier',
                 LGBMClassifier(max_depth=12, n_estimators=170,
                                num_leaves=22))])
The mean accuracy of the model is through randomized search is : 0.6454518654394182
time: 619 ms


In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,classification_report


time: 7 ms


In [15]:
best_model_r.best_params_

{'classifier': LGBMClassifier(max_depth=12, n_estimators=170, num_leaves=22),
 'classifier__max_depth': 12,
 'classifier__n_estimators': 170,
 'classifier__num_leaves': 22}

time: 25 ms


In [16]:
rfc=LGBMClassifier(max_depth=12, n_estimators=170,
                                num_leaves=22,random_state=96)
rfc.fit(X_train,y_train)
y_train_pred=rfc.predict(X_train)
y_train_prob=rfc.predict_proba(X_train)[:,1]

y_test_pred=rfc.predict(X_test)
y_test_prob=rfc.predict_proba(X_test)[:,1]

print('Confusion Matrix-Train\n',confusion_matrix(y_train,y_train_pred))
print('Accuracy Score-Train\n',accuracy_score(y_train,y_train_pred))
print('Classification Report-Train\n',classification_report(y_train,y_train_pred))

print('\n'*2)
print('Confusion Matrix-Test\n',confusion_matrix(y_test,y_test_pred))
print('Accuracy Score-Test\n',accuracy_score(y_test,y_test_pred))
print('Classification Report-Test\n',classification_report(y_test,y_test_pred))



Confusion Matrix-Train
 [[28310  9971]
 [13232 19721]]
Accuracy Score-Train
 0.6742707134233652
Classification Report-Train
               precision    recall  f1-score   support

           0       0.68      0.74      0.71     38281
           1       0.66      0.60      0.63     32953

    accuracy                           0.67     71234
   macro avg       0.67      0.67      0.67     71234
weighted avg       0.67      0.67      0.67     71234




Confusion Matrix-Test
 [[11860  4720]
 [ 6104  7845]]
Accuracy Score-Test
 0.6454518654394182
Classification Report-Test
               precision    recall  f1-score   support

           0       0.66      0.72      0.69     16580
           1       0.62      0.56      0.59     13949

    accuracy                           0.65     30529
   macro avg       0.64      0.64      0.64     30529
weighted avg       0.64      0.65      0.64     30529

time: 1min 12s


In [17]:
lgbm = LGBMClassifier(max_depth=12, n_estimators=170,
                                num_leaves=22,random_state=96)

models=[]
models.append(('lgbm',lgbm))

time: 3 ms


In [21]:
from sklearn import model_selection
import matplotlib.pyplot as plt
import seaborn as sns

time: 200 ms


In [23]:
def algorithim_boxplot_comparison(X,
                                  y,
                                  algo_list=[],
                                  random_state=96,
                                  scoring='accuracy',
                                  n_splits=10):
    """To compare metric of different algorithims
       Paramters-
       algo_list : a list conataining algorithim models like random forest,
                     decision trees etc.
       X : dataframe without Target variable
       y : dataframe with only Target variable
       random_state : The seed of randomness. Default is 3
       n_splits : Number of splits used. Default is 3
       ( Default changes from organization to organization)
       Returns-
       mean accuracy and the standard deviation accuracy.
       Box Plot of Acuuracy"""

    results = []
    names = []
    for algo_name, algo_model in algo_list:
        kfold = model_selection.KFold(shuffle=True,
                                      n_splits=n_splits,
                                      random_state=random_state)
        cv_results = model_selection.cross_val_score(algo_model,
                                                     X,
                                                     y,
                                                     cv=kfold,
                                                     scoring=scoring)
        results.append(cv_results)
        names.append(algo_name)
        msg = "%s: %s : (%f) %s : (%f) %s : (%f)" % (
            algo_name, 'median', np.median(cv_results), 'bias',
            1-np.mean(cv_results), 'variance', cv_results.var(ddof=1))
        print(msg)
    # boxplot algorithm comparison
    fig = plt.figure()
    fig.suptitle('Algorithm Comparison')
    ax = fig.add_subplot(111)
    plt.boxplot(results)
    ax.set_xticklabels(names)
    plt.show()


time: 44 ms


In [24]:
algorithim_boxplot_comparison(X,y,algo_list=models)